# Creates a release branch whenever a release is created.

name: On Release Created
on:
  release:
    types:
      - published

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Note: Needed in order to generate a tag on the associated commit.
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ github.event.release.tag_name }}'

  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ifc.tex
          working_directory: ltx

      - name: Add PDF to Release
        uses: softprops/action-gh-release@v0.1.13
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ltx/ifc.pdf
