# Creates a release branch whenever a release is created.

name: On Release Created
on:
  release:
    types:
      - published

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Note: Needed in order to generate a tag on the associated commit.
    steps:
      - uses: peterjgrainger/action-create-branch@4b81ce657e255acd677cc6c55c9c763654be3aef # v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ github.event.release.tag_name }}'

  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Compile document
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # 4.1.0
        with:
          root_file: ifc.tex
          working_directory: ltx

      - name: Add PDF to Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ltx/ifc.pdf
