# Creates or updates a release's generated PDF when a change occurs
# to a release branch
name: Update Existing Release
on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "RELEASE_NAME=$(echo ${GITHUB_REF#refs/heads/release/})" >> $GITHUB_ENV

      - name: Extract changelog (comparing with main branch)
        shell: bash
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git log $(git merge-base origin/main HEAD)..HEAD --pretty=format:"[\`%h\`]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/%h) %s (%aN)" >> $GITHUB_ENV
          echo >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ifc.tex
          working_directory: ltx

      - name: Update release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          files: ltx/ifc.pdf
          generate_release_notes: false
          body: |
            ## Changelog
            ${{ env.CHANGELOG }}

