# Creates a release branch whenever a release is created.

name: Create Release Branch
on:
  release:
    types:
      - published

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ github.event.release.tag_name }}'
